# metadata specialised for each experiment
core:
  version: 0.1.0
  tags:
    - change-loss

defaults:
  - data: default
  - hydra: default
  - logging: default
  - model: pixel
  - optim: default
  - train: default
  - physics: default
#    Decomment this parameter to get parallel job running
#  - hydra/launcher: joblib
